before_script:
  - cp config/database.yml.example config/database.yml
  - cp .env.example .env
  - psql -c 'create database "fec-graph-search_test";' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
bundler_args: --without development
language: ruby
rvm:
  - ruby-2.1.2
services:
  - redis
  - neo4j
addons:
  code_climate:
    repo_token: d0d76f9cdecf7c06a43ede612fc4be667b21cb7142d896dde21c2771c47b4bdc 